name: ubuntu with apt-get

on: [push]

jobs:
  ubuntu--apt-get:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: boost install
      run: sudo apt-get install libboost-all-dev
    - name: configure
      run: cmake -S . -B build -DCMAKE_CXX_FLAGS="-Werror" -DBUILD_TESTING=ON
    - name: build
      run: cmake --build build
    - name: test
      run: cd build && ctest
