name: workflow on ubuntu

on: [push]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: boost install
      run: sudo apt-get install libboost-all-dev
    - name: configure
      run: cmake -S . -B build -DCMAKE_CXX_FLAGS="-Werror"
    - name: build
      run: cmake --build build
    - name: test
      run: cd build && ctest
