name: windows with vcpkg

on: push

jobs:
  build-on-windows:
    runs-os: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        buildtype: [Release]
        include:
          - os: windows-latest
            triplet: x64-windows
            vcpkgCommitId: 'ee17a685087a6886e5681e355d36cd784f0dd2c8'
            vcpkgPackages: 'boost-test'
    
    steps:
      - uses: actions/checkout@v1

      - uses: lukka/get-cmake@latest

      - name: Restore artifacts, or run vcpkg, build and cache artifacts
        uses: lukka/run-vcpkg@master
        id: runvcpkg
        with:
          vcpkgArguments: '${{ matrix.vcpkgPackages }}'
          vcpkgTriplet: '${{ matrix.triplet }}'
          vcpkgDirectory: '${{ runner.workspace }}/b/vcpkg'
          vcpkgGitCommitId: '${{ matrix.vcpkgCommitId }}'

      - name: Prints outputs of run-vcpkg task
        run: echo "'${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT }}' '${{  steps.runvcpkg.outputs.RUNVCPKG_VCPKG_TRIPLET_OUT }}' "

      - name: Building with CMake
        uses: lukka/run-cmake@v2
        with:
          useVcpkgToolchainFile: true
          cmakeListsTxtPath: '${{ github.workspace }}/src/CMakeLists.txt'
          buildDirectory: ${{ runner.workspace }}/src/build
          cmakeBuildType: ${{ matrix.buildtype }}
          
        
      
    