name: windows with vcpkg

on: push

jobs:

  build-on-windows:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]
        buildtype: [Release]
        include:
          - os: windows-latest
            triplet: x64-windows
            vcpkgCommitId: 'ee17a685087a6886e5681e355d36cd784f0dd2c8'
            vcpkgPackages: 'boost-test'
    
    steps:
      - uses: actions/checkout@v1

      - uses: lukka/get-cmake@latest

      - name: Restore artifacts, or run vcpkg, build and cache artifacts
        uses: lukka/run-vcpkg@master
        with:
          vcpkgArguments: '${{ matrix.vcpkgPackages }}'
          vcpkgTriplet: '${{ matrix.triplet }}'
          vcpkgDirectory: '${{ runner.workspace }}/b/vcpkg'
          vcpkgGitCommitId: '${{ matrix.vcpkgCommitId }}'

      - name: Prints outputs of run-vcpkg task
        run: echo "'${{ steps.runvcpkg.outputs.RUNVCPKG_VCPKG_ROOT_OUT }}' '${{  steps.runvcpkg.outputs.RUNVCPKG_VCPKG_TRIPLET_OUT }}' "

      - name: Building with CMake
        uses: lukka/run-cmake@v2
        with:
          useVcpkgToolchainFile: true
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          buildDirectory: ${{ github.workspace }}/build
          cmakeBuildType: ${{ matrix.buildtype }}
      
      - name: where am i
        run: echo "%cd%"
      
      - name: list dir
        run: dir
        
      # - name : go up and look around
      #  run: |
      #       cd ..
      #       dir
        
      #- name: Test
      #  run: ctest
      
    